export const metadata = {
  title:{
    template:" %s | Create Next App",
    default: 'Create Next App'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   <>
       <header style={{backgroundColor:"Orange",padding:"10px"}}>Header (Application)</header>
        {children}
        <footer style={{backgroundColor:"green",padding:"10px"}}>Footer (Application)</footer>
    </>
  );
}
