export const metadata = {
  title:{
    template:" %s | Create Next App",
    default: 'Create Next App'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
